name: Build
on:
  push:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@main
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Set up JDK 22
      uses: actions/setup-java@main
      with:
        java-version: 22
        distribution: temurin
        
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@main
      with:
        gradle-version: "current"
        
    - name: Build with Gradle
      run: gradle assembleRelease

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@main
      with:
        name: PMPatch
        path: module/build/outputs/*
